language: node_js

node_js:
  - "stable"

addons:
  firefox: "latest-beta"

before_script:
  - firefox -v
  - cd $TRAVIS_BUILD_DIR
  - mozilla-download --branch mozilla-central --product firefox firefox
  - export FIREFOX_PATH=$TRAVIS_BUILD_DIR/firefox/firefox
  - echo $FIREFOX_PATH
  - sleep 10
  - find firefox
  - export PATH=$FIREFOX_PATH:$PATH
  - echo $PATH
  - export JPM_FIREFOX_BINARY=`which firefox`
  - echo $JPM_FIREFOX_BINARY
  - firefox -v
